application:
  name: n8n
  project: dbdmn8n
  publicly_accessible: true
  storage:
  - name: "n8n"
    size: "20"
    type: "ssd"
    mount_point: "/var/"
databases:
- type: postgresql
  version: 12
  name: dbdmn8n-database
routers:
- name: main
  routes:
  - application_name: n8n
    paths:
    - /*
