application:
  name: n8n
  project: dbdmn8n
  publicly_accessible: true
databases:
- type: postgresql
  version: 12
  name: dbdmn8n-database
routers:
- name: main
  routes:
  - application_name: n8n
    paths:
    - /*
